[package]
name = "fuzzycomp"
version = "0.2.0"
authors = ["Juroj Robba <jurij.robba@vernocte.org>"]
edition = "2018"
license = "MIT"
keywords = ["fuzzy", "comp"]
categories = ["mathematics", "no-std", "science"]
description = "Comparison with margins"


[dependencies]

# None
